---
# tasks file for docker
- name: VIEW ALL ANSIBLE FACT KEYS
  debug:
    msg: "{{ ansible_facts }}"

- name: "Remove All Deprecated/ Install Docker"
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine


- name: "Install yum-utils"
  yum:
    name: yum-utils
    state: present

- name: "Add Repository repo yum-config-manager"
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: "DNF package update containerd.io"
  yum:
    name: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm"
    state: present

- name: "Yum install Docker"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Start Docker Service"
  systemd:
    name: docker
    state: reloaded
    enabled: yes

- name: "Add ansible_user (login user) to docker group"
  user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups:
      - docker
    append: yes

- name: "Install Git & Python"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3
    - python3-pip

- name: "pip install docker-compose"
  pip:
    name: docker-compose
    state: present
    
  # - name: "CURL docker-compose"
  #   get_url:
  #     url: "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}"
  #     dest: "/usr/local/bin/docker-compose"

  # - name: "Add permission to docker-compose inorder to run execute bin command"
  #   file:
  #     path: /usr/local/bin/docker-compose
  #     mode: +x

  # - name: "Add Symbolik Link to docker-compose bin /usr/bin"
  #   file:
  #     state: link
  #     src: /usr/local/bin/docker-compose
  #     dest: /usr/bin/docker-compose
